# vim:ft=kitty

## name: Theodolite
## author: mrwild
## blurb: Dark theme of rich colors with gold accents and text. Meant to invoke the feeling of watching the sunset from a warmly lit library. No muted tones. Pairs well with backgrounds of space photography and the art of Jocelin Carmes.

#: All the settings below are colors, which you can choose to modify, or use the
#: defaults. You can also add non-color based settings if needed but note that
#: these will not work with using kitty @ set-colors with this theme. For a
#: reference on what these settings do see https://sw.kovidgoyal.net/kitty/conf/

#: The basic colors

foreground                      #F5DA91
background                      #110F1A
selection_foreground            #110F1A
selection_background            #eab63e


#: Cursor colors

cursor                          #eab63e
cursor_text_color               #110F1A
cursor_trail_color              #2B91AE


#: URL underline color when hovering with mouse

url_color                       #2B91AE


#: kitty window border colors and terminal bell colors

active_border_color             #EAB63E
inactive_border_color           #371C62
bell_border_color               #CF8126
visual_bell_color               #E19439


#: OS Window titlebar colors

wayland_titlebar_color          system
macos_titlebar_color            system


#: Tab bar colors

active_tab_foreground           #110F1A
active_tab_background           #EAB63E
inactive_tab_foreground         #F5DA91
inactive_tab_background         #371C62
tab_bar_background              none
tab_bar_margin_color            none


#: Colors for marks (marked text in the terminal)

mark1_foreground #110F1A
mark1_background #2B91AE
mark2_foreground #110F1A
mark2_background #FDF0CD
mark3_foreground #110F1A
mark3_background #81154C


#: The basic 16 colors

#: black
color0 #4F2707
color8 #6D3B13

#: red
color1 #6A0D3C
color9 #8E2058

#: green
color2  #0A6C4C
color10 #2C9C77

#: yellow
color3  #CF8126
color11 #F3AF5F

#: blue
color4  #355EAD
color12 #4A73C1

#: magenta
color5  #533484
color13 #634494

#: cyan
color6  #2B91AE
color14 #44ABC8

#: white
color7  #F5DA91
color15 #FDF0CD
